# Generated by Django 3.2.3 on 2021-07-10 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=250)),
                ('option_one', models.CharField(max_length=250)),
                ('option_two', models.CharField(max_length=250)),
                ('option_three', models.CharField(max_length=250)),
                ('option_four', models.CharField(max_length=250)),
                ('option_one_votes', models.IntegerField(default=0)),
                ('option_two_votes', models.IntegerField(default=0)),
                ('option_three_votes', models.IntegerField(default=0)),
                ('option_four_votes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
